server:
  port: 8082

spring:
  application:
    name: song-service

  datasource:
    url: jdbc:postgresql://172.31.33.20:5433/song-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
