server:
  port: 8081

spring:
  application:
    name: resource-service

  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://${WSL_DB_HOST:localhost}:5432/resource-db}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres}"
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

song-service:
  url: "${SONG_SERVICE_URL:http://localhost:8082}"
