server:
  port: 8081

spring:
  application:
    name: resource-service

  datasource:
    url: jdbc:postgresql://localhost:5432/resource-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Song Service URL for communication
song-service:
  url: http://localhost:8082
